version: '3.8'
services:
  db:
    image: 'postgres:15.0-alpine'
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-api}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1234}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: api/fastapi:v1
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-1234}
      - DATABASE_NAME=${DATABASE_NAME:-api}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
volumes:
  postgres_data:
